# Generated by Django 5.2 on 2025-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
